### ISSUE TITLE
[Enhancement]: decouple lib/log.js  

### ISSUE THREAD

**Issue by hemal7735** [bnb/good-first-issue#51]
Currently, `lib/log.js` is iterating over `issues` and forms `output` array.
I see the oppurtunity of enhancement from both performance and modularity here.

**If the `log` module just create the output from `issue`, and `project` objects then,**
1. We can avoid generating output for all issues --> perf  boost, we can get some benchmark 😉 
2. We can test is easily --> modularity

@bnb @maddhruv your thoughts are welcome ! 💯 

if possible I would like to work on that as well.

**Comment by bnb** [comment]
@hemal7735 I've been thinking about how we're iterating over a large set of objects. 


As I'm writing this, I just switched away from working on filtering for `search.js` and I'm realizing that we're only iterating over either 30 or 100 issues rather than the 50k that are open for that (which explains why there were some very commonly occurring repos when I was testing).

Would ❤️ to have your help on this if you'd like to take a stab at it!

A quick, additional thought:

The intent of `lib/log.js` is to produce a truly random issue – in the case of `feeling-lucky`, we're only doing that with a limited subset. As far as I know, all other projects are with in the `per_page` limit defined by [@octokit/rest.js](https://octokit.github.io/rest.js/#api-Search-issues)'s Issue Search. I would like to ensure that we are truly producing a random issue. Killing two birds with one stone here would be the smart thing, if possible 👍

**Comment by hemal7735** [comment]
@bnb I see there is a field called `total_count` in the response. We can utilize that to figure out the number of pages as default is 30 items per page. So the idea is:
1. figure out the number of pages
2. select random page
3. select random issue from that page

We will be making 2 calls to octokit apis for this. I'm not sure how it will affect rate-limiting.

**Comment by hemal7735** [comment]
Should not the intent of the `lib/log.js` is to create a loggable string from the issue passed as parameter ? and not select the project?

**Comment by bnb** [comment]
Which line specifically are you referring to when you're talking about selecting the project @hemal7735? 🤔

As far as I can tell that's not currently the case – the `project` argument is only to pass in the name of the project. Could be wrong though 👍

**Comment by hemal7735** [comment]
PR is merged. Closing the issue.
